FROM amazoncorretto:8-alpine-jdk
MAINTAINER flacosakeo
COPY C:/Users/flaco/OneDrive/Escritorio/curso/ProyectoFinal/BackEnd/target/ERL-0.0.1-SNAPSHOT.jar ERL-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/ERL-0.0.1-SNAPSHOT.jar"]